### ISSUE TITLE
Authentication Required button not visible in Edge

### ISSUE THREAD

**Issue by Carus11** [sassoftware/visual-analytics-sdk#11]
Version: 0.3
When testing the authenticationMode="credentials" with an unauthenticated browser session chrome shows a button that says Login...
When testing the same in Edge there is no login button or wording asking for authentication required

Edge Version 41.16299
![image](https://user-images.githubusercontent.com/4925828/74183648-99ab3000-4c02-11ea-8594-f890bc0bcbc2.png)

There is an error in the console, maybe related?
![image](https://user-images.githubusercontent.com/4925828/74183730-be070c80-4c02-11ea-8f11-5680eabd0592.png)

**Comment by brmorr** [comment]
Did you include the custom elements polyfill, as instructed in the [getting started](https://developer.sas.com/sdk/va/docs/getting-started/#include-a-custom-elements-polyfill) doc?

**Comment by Carus11** [comment]
Ah yeah that was it, Thanks.
