### ISSUE TITLE
Compilation fails with react app

### ISSUE THREAD

**Issue by aswin-s** [sassoftware/visual-analytics-sdk#12]
I'm trying to import sas-va-report objects like so
```jsx
import { registerDataDrivenContent } from '@sassoftware/va-report-components'
```
But the compilation fails with below error
```bash
Failed to compile.

./node_modules/@sassoftware/va-report-components/dist/esm/fonts/sas-icons-regular.ttf
Error: ENOENT: no such file or directory, open '/app/node_modules/@sassoftware/va-report-components/dist/esm/fonts/sas-icons-regular.ttf'
```
Sample Repo:
https://github.com/aswin-s/sas-report-demo

I couldn't find any examples which use the import format for loading SAS data driven content. Can someone shed some light here?

**Comment by brmorr** [comment]
There are some issues with using the ESM build, and we are in the process of removing it from the package.  The suggested approach with a react app would be to use the Web Component api.  Add a script to load va-report-components.js to your index.html.  This could be either from the CDN or locally after an npm install.  Then in your react components just render the `<sas-report>`, `<sas-report-object>`, or `<sas-report-page>` tag directly.
