### ISSUE TITLE
sdk with credentials samesite cookie

### ISSUE THREAD

**Issue by EPKGames** [sassoftware/visual-analytics-sdk#21]
Hello,

We are running in an issue where on new versions of google chrome samesite cookie must be "None" and "Secure".
[https://www.chromium.org/updates/same-site](https://www.chromium.org/updates/same-site)

error:
![image](https://user-images.githubusercontent.com/29751980/88928863-9f143980-d279-11ea-9619-d336f0758459.png)
(lang: dutch)

problem:
![image](https://user-images.githubusercontent.com/29751980/88929003-ce2aab00-d279-11ea-894c-2272924187c5.png)
![image](https://user-images.githubusercontent.com/29751980/88929183-1053ec80-d27a-11ea-96d3-6e6e2ba64f18.png)

So as you can see we can put the cookie in samesite=none but google also wants the cookie to be secure. 
However I have not been able to find any solutions for this problem.

What we have on our server:
![image](https://user-images.githubusercontent.com/29751980/88929419-62950d80-d27a-11ea-937b-ee84eb01842e.png)
(lang: dutch)

Is there any work around this problem or a fix?

thank you for reading our problem, I hope you can help us!

**Comment by brmorr** [comment]
Cookies are only set as 'secure' when running over https.  So in this case, your Viya installation needs to be setup with TLS enabled and accessed using http from the SDK.  This should automatically set `secure` on the cookie.

**Comment by EPKGames** [comment]
Thank you for your response. we havn't fixed it yet but it's a work in progress.

**Comment by brmorr** [comment]
I have verified on our own internal systems that `secure` does get added when running over https.  Marking this issue closed.
