### ISSUE TITLE
"Unauthorized" (status 401) error when loading the report through sas-va-sdk

### ISSUE THREAD

**Issue by youbao88** [sassoftware/visual-analytics-sdk#28]
Hej there

We have been using sas va to test a report on a prep environment (https://prep.vardcentraler.sll.se/test-sas/). 

We found that by using old version of Chome (78.0.3904.87 32 bit), the report can not be loaded.
SAS VA: 8.5.1
SAS VA SDK: 0.10.0

![error](https://user-images.githubusercontent.com/39054561/98002105-fb917280-1ded-11eb-8b0a-7ed24f5e0b36.jpg)

![bug](https://user-images.githubusercontent.com/39054561/98002916-6478ea80-1dee-11eb-8896-5c08f8b41b95.jpg)

Request URL: https://slso-atea.saasnow.com/SASLogon/oauth/authorize?client_id=sas.identities&redirect_uri=/identities/users/@currentUser&response_type=code&state=57c1ae6e
Request Method: GET
Status Code: 401 

error: "Unauthorized"
message: "Full authentication is required to access this resource"
path: "/SASLogon/oauth/authorize"
status: 401
timestamp: 1604409032332

It's worth to be mentioned that this problem only occurred with 32 bit old Chrome version, not with the latest 64 bit Chrome or Edge. 

Thank you for your assistance in advance.

**Comment by youbao88** [comment]
Hi
Thank you for your replay. Absolutely!

Chrome: Windows 10, Chrome 78.0.3904.87 (32bit)
Safari: Mac OS 10.14.6 Safari Version 14.0 (14610.1.28.1.10)

A little bit update of this bug:
When using Mac Safari, it says "Failed to load resource: too many HTTP redirects"
<img width="1367" alt="Screen Shot 2020-11-14 at 12 01 04" src="https://user-images.githubusercontent.com/39054561/99145693-293dad80-2671-11eb-9287-bf863b9a11ad.png">
<img width="1423" alt="Screen Shot 2020-11-14 at 12 03 45" src="https://user-images.githubusercontent.com/39054561/99145740-7e79bf00-2671-11eb-8b8c-1039ee8883f2.png">

This issue can be fixed in safari if you go into the preference and disable 'prevent cross-site tracking'
<img width="834" alt="Screen Shot 2020-11-14 at 12 05 06" src="https://user-images.githubusercontent.com/39054561/99145779-be40a680-2671-11eb-834b-287de8970405.png">

But, we would not recommend our users to disable this settings just in order to visit our website. Moreover, I am not very clear if this issue was related to issue from old version chrom.

FYI, we have updated the domain of our prep environment and now it is  https://prep.slso.sll.se/test-sas/.

Thank you again for your help!

Minhao Zhou

**Comment by brmorr** [comment]
This looks like it is probably an issue with how the Viya server is configured.  Have you followed the steps listed here, https://developer.sas.com/sdk/va/docs/getting-started/#sas-viya-setup.

What version of Viya are you trying to connect to?

**Comment by youbao88** [comment]
Hi

Yes, we do follow the steps from va sdk's configuration page. Our sas viya environment is: V.03.05

Best regards,

**Comment by brmorr** [comment]
I am using Chrome 86 (64bit) on my mac and verified your site is working fine for me.  So certainly not a config issue.  You mentioned it was v78 32bit.  Can you try the latest 32bit version and see if that works?

**Comment by youbao88** [comment]
Hi!

Sorry for the late response. I tested it with the latest version Chrome 32 bit and it works fine with that version.

However, do you have any solutions for that issue from Mac Safari?

**Comment by brmorr** [comment]
It is possible that we are hitting [this issue](https://www.chromium.org/updates/same-site/incompatible-clients). Note that it says 

_"Versions of Safari and embedded browsers on MacOS 10.14 and all browsers on iOS 12. These versions will erroneously treat cookies marked with `SameSite=None` as if they were marked `SameSite=Strict`. This bug has been fixed on newer versions of iOS and MacOS."_

But I am running MacOS 10.15.6 and seeing the problem as well, and it sounded like this was fixed at versions newer than 10.14.

**Comment by youbao88** [comment]
Hi

Thank you again for your answers.

Yes, it seems very confusing to me. I am running the latest safari and iOS (14.2)on my iPhone. However, there appears the same issue.

**Comment by devaKumaraswamy** [comment]
Chrome had options to turn off the checking for same-site cookies - maybe Safari has similar flags - worth a try.

**Comment by brmorr** [comment]
Deva, the chrome option allows the client to ignore the missing samesite attribute on the cookie, but we know for seeing this working in Chrome (and inspecting its cookies) that the samesite attr is present, and correctly set to None.  But then when I ran on Safari I did not see the samesite attr listed.  And see the screenshot above.  It was mentioned that turning off "Prevent cross-site tracking" allows it to work.

It is unclear what "prevent cross-site tracking" is supposed to do.  If it is intended to disallow all cross-site cookies, regardless of the samesite attrs, then that indeed would be a problem for the VASDK.  The VASDK uses cookies to establish  authentication, and without it you would get the behavior seen here.

And also note that while I see the issue when running in Safari against https://prep.slso.sll.se/test-sas/ I do not see it when running against our internal development server.  I'm not yet sure why that is.

**Comment by brmorr** [comment]
I took a look at this again, and I realized that my test against the internal server was using authenticationType="credentials".  When I change that to authenticationType="guest" I get the same problem that you are seeing.  Can you confirm that if you change to use credentials that it works for you?

**Comment by youbao88** [comment]
Hej there

Nice. We would test it ASAP. However, our prep environment (prep.slso.sll.se)is currently undergoing some maintenance. I would update the tag as soon as it is finished!

**Comment by youbao88** [comment]
Hi 
I comfirmed that when it is changed to 'credentials', it works fine on Mac Safari. 
However, I think this might not be a solution for this issue since our website is for public to visit. 
<img width="1323" alt="Screen Shot 2020-12-07 at 11 37 56" src="https://user-images.githubusercontent.com/39054561/101341291-25bcd100-3881-11eb-9929-e7438cb0778c.png">
<img width="1323" alt="Screen Shot 2020-12-07 at 11 39 19" src="https://user-images.githubusercontent.com/39054561/101341298-2b1a1b80-3881-11eb-8442-74197093330b.png">
Thank you again!

**Comment by brmorr** [comment]
As another data point, I also saw that this works fine when running against a SAS Viya 3.5 system.  That can be seen in the SDK usage here, https://globalbusinessbarometer.economist.com/, where guest mode works with Safari even with the "Prevent cross-site tracking" enabled.

I have created an internal issue to further investigate this.  It seems like it may be a server issue, and not a direct issue with the SDK.

The credential login does allow users to chose guest from the login popup, so maybe that is an option for your safari users, until we get this bug fixed.  To minimize the impact you may be able to conditionally set authorization="credentials", only when the browser is detected to be safari.

**Comment by youbao88** [comment]
Hi Brad!

That sounds like a good temporary solution for this issue. I am going to implement this and write some info for the users. Thank you again for your assistance.

Best wishes

Minhao Zhou

**Comment by brmorr** [comment]
Since there is this potential temporary workaround, and we have an separate issue to track the server side problem, I'm going to close this issue.
