### ISSUE TITLE
Report no response when updating parameters and change the page

### ISSUE THREAD

**Issue by youbao88** [sassoftware/visual-analytics-sdk#38]
Hi there

We found that if we call the updateReportParameters method and then change the page, the whole web page  would be no reponse.
Here are some debug information from Chrome Dev tool. 
![Skärmklipp](https://user-images.githubusercontent.com/39054561/112632384-588ed300-8e38-11eb-9915-5fffd24110a4.PNG)
![Skärmklipp2](https://user-images.githubusercontent.com/39054561/112632416-647a9500-8e38-11eb-9f05-a6ba8f93878f.PNG)

SAS Viya V.03.05
SAS Visual Analytics 8.5.1
SAS VA SDK 0.10.0

Thank you in advance,

**Comment by brmorr** [comment]
Unfortunately that doesn't give much to go on.  Can you upgrade the SDK to the latest, v0.15.0, and see if you still have the same issue?

Also, can you give any details about the report, the parameter that is being set, what that parameter controls in the report, and what value you are setting?

**Comment by youbao88** [comment]
Hi

Thank you for your feedbacks. We tried with v0.15.0 and the problem is still there.

You can access to our report via this [link](https://prod14.slso.sll.se/analysverktyg/?id=138423). Let's pick one of the parameter for this example. The parameter 'karta_Tidsperiod' (ENG: map_timeperiod) controls the value in the 'Karta' (ENG map) page's '4. Välj tidsperiod' selection box. If you call updateReportParameters method on the 'Karta' page, it works. However, if you call the method on other pages and switch to 'Karta' page, the report will have no response.

**I also included a [video](https://www.dropbox.com/s/6sjm2jiv19q8n7m/sas_va_sdk_issue.mp4?dl=0) here to show this issue.** 
Thank you for your help in advance.

**Comment by brmorr** [comment]
@youbao88 I am just getting back to this to dig deeper, but that link to your app no longer works. Do you have an updated link to reproduce this?

**Comment by youbao88** [comment]
Hi

Yes, here it is a new link. https://prod14.slso.sll.se/webbverktyg/?id=138425#.

Moreover, I  thought I know more about this bug. This bug only appears for the page with 'drop-down' list. In our report, you can see that I have now changed all the 'drop-down list' to a prompt container with list control. Then, this bug disappears. So I am suspecting that there is something wrong about 'list-control' when you call updateReportParameter method and change the page.

**Comment by brmorr** [comment]
@youbao88, thank you for the extra information on how to reproduce the issue.  We will be investigating this and will report back here with any updates.

**Comment by brmorr** [comment]
@youbao88, this was fixed back in our Jun 16 release (v0.18.0).  Sorry that I didn't update you on this. Please let us know if this is not working for you in the latest release.
