### ISSUE TITLE
Bug- When you de-select the item in a required multi-selection list control, it would mistakely select all

### ISSUE THREAD

**Issue by youbao88** [sassoftware/visual-analytics-sdk#42]
Hi

I just noticed a bug which could be caused by VA SDK. I have uploaded a video to show this bug.

In our report, there is a list-control which are used to filter the areas in the line-plot (If you select one area, there would be one line. If you select two areas, there would be two lines). That list control is wrapped in a prompt container. Moreover, that list control is set to 'required', and 'allow multi selection'.

Now, when we have only one selected area in that list control and we further click on area one more time, the report would surprisingly select all the items although it is now shown in the list control. I have tried this directly inside SAS Visual Analytics and there is no such problem there. Thus, I am wondering this could be a bug with VA SDK. 

I have tried this with version 0,16,0 and the problem is still the same.

Thank you! 

https://user-images.githubusercontent.com/39054561/118773502-32f4d780-b885-11eb-8b0e-769c65ba2ab3.mp4

**Comment by brmorr** [comment]
Yes, that is a bug, and our internal testing had also recently found this issue.  I see that this has been fixed and should be part of our v0.17.0 release later today.  Once that has been released, please try it and see if this issue is fixed.

**Comment by youbao88** [comment]
Hi

Thank you. Yes, I tried it with v0.17.0 and it is fixed! I am going to close this issue. Thank you again for fixing this bug.

**Comment by brmorr** [comment]
Great news!  Thanks for closing the issue.
