### ISSUE TITLE
Using SASReportElement does not pick up the Report Name/Title as show in the SASVisualAnalyticsApp

### ISSUE THREAD

**Issue by jpletzke** [sassoftware/visual-analytics-sdk#78]
Following the code examples a VA SDK set of resources have been created. When displaying the SASReportElement within HTML, the Report Name/Title does not appear in the browser. We have tried playing with the hidenavigaton option, but that only shows/hides the Report Pages (Tabs) and not the Title that appears above the Pages in the SASVisualAnalytics application. How can we display the Report Title in the SDK so that it matches what is seen in the application?

**Comment by brmorr** [comment]
Rendering the report title is not part of the behavior of the VASDK.  This is intended behavior, as the VASDK is meant to render the report content only.  One could simply add HTML text directly to the page, above the report, in order to get this desired behavior.
